// Generated by gencpp from file turtlebot3_autorace_msgs/DetectResult.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_AUTORACE_MSGS_MESSAGE_DETECTRESULT_H
#define TURTLEBOT3_AUTORACE_MSGS_MESSAGE_DETECTRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_autorace_msgs
{
template <class ContainerAllocator>
struct DetectResult_
{
  typedef DetectResult_<ContainerAllocator> Type;

  DetectResult_()
    : label()
    , x(0.0)
    , y(0.0)
    , width(0.0)
    , height(0.0)  {
    }
  DetectResult_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , x(0.0)
    , y(0.0)
    , width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> const> ConstPtr;

}; // struct DetectResult_

typedef ::turtlebot3_autorace_msgs::DetectResult_<std::allocator<void> > DetectResult;

typedef boost::shared_ptr< ::turtlebot3_autorace_msgs::DetectResult > DetectResultPtr;
typedef boost::shared_ptr< ::turtlebot3_autorace_msgs::DetectResult const> DetectResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator1> & lhs, const ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator1> & lhs, const ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_autorace_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a586ac5639038eb78db980bd409a7e6";
  }

  static const char* value(const ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a586ac5639038ebULL;
  static const uint64_t static_value2 = 0x78db980bd409a7e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_autorace_msgs/DetectResult";
  }

  static const char* value(const ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n"
"float64 x\n"
"float64 y\n"
"float64 width\n"
"float64 height\n"
;
  }

  static const char* value(const ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_autorace_msgs::DetectResult_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_AUTORACE_MSGS_MESSAGE_DETECTRESULT_H
